INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (101, 'COMPANY1', 1000);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (102, 'COMPANY2', 3000);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (103, 'EMPLOYEE1', 10);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (104, 'EMPLOYEE2', 0);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (105, 'EMPLOYEE3', 0);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (106, 'EMPLOYEE4', 0);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (107, 'EMPLOYEE5', 0);
INSERT INTO ACCOUNT (ID, NAME, BALANCE) VALUES (108, 'EMPLOYEE6', 0);